name: Test.CI

on: [push]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Nuget Restore
      run: nuget restore PassZipper.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild PassZipper.sln -p:Configuration=Release
